### ISSUE TITLE
All Forge:FilledBucket items shapeless craft into Tar Drops

### ISSUE THREAD

**Issue by katubug** [FossilsArcheologyRevival/FossilsArcheologyRevival#1353]
I noticed as I accidentally added every bucket to an ore dictionary registry (lol) that any bucket that has the item id forge:filledbucket will craft into 4 tar drops when placed in a crafting grid. The exception is when there is another recipe conflicting with that.

Versions:
fossilsarcheology-8.0.0
llibrary-1.7.19-1.12.2
forge-1.12.2-14.23.5.2838-universal

**Comment by Alex-the-666** [comment]
fixed in 8.0.1 i believe

**Comment by katubug** [comment]
This issue is still present in 8.0.2.

|![2019-07-12_09 45 00](https://user-images.githubusercontent.com/20935286/61136768-cab75c80-a489-11e9-80a8-57993659b400.png)
